[program:proxies]
command=/home/hashwalker/proxies/.venv/bin/python -m proxies.main
directory=/home/hashwalker/proxies/
autostart=true
autorestart=true
environment=PYTHONUNBUFFERED="1"

stderr_logfile=/home/hashwalker/proxies/proxies/proxies.out.log
stdout_logfile=/home/hashwalker/proxies/proxies/proxies.out.log
user=root
logfile_maxbytes=1MB
logfile_backups=10

[program:proxies_switcher]
command=/home/hashwalker/proxies/.venv/bin/python -m proxies.switcher
directory=/home/hashwalker/proxies/
autostart=true
autorestart=true
environment=PYTHONUNBUFFERED="1"

stderr_logfile=/home/hashwalker/proxies/proxies/proxies_switcher.out.log
stdout_logfile=/home/hashwalker/proxies/proxies/proxies_switcher.out.log
user=root
logfile_maxbytes=1MB
logfile_backups=10
